### ISSUE TITLE
Image is not auto-adjusting for 1080x1920 (portrait)

### ISSUE THREAD

**Issue by zDEFz** [gergo-salyi/multibg-sway#9]
Works fine with 16x9, have exactly defined wallpaper to be 1080x1920px, still no luck.

Maybe add a option for auto-zoom.

```bash
 mediainfo 1.png
General
Complete name                            : 1.png
Format                                   : PNG
Format/Info                              : Portable Network Graphic
File size                                : 1.84 MiB

Image
Format                                   : PNG
Format/Info                              : Portable Network Graphic
Compression                              : Deflate
Format settings                          : Linear
Width                                    : 1 080 pixels
Height                                   : 1 920 pixels
Display aspect ratio                     : 0.562
Color space                              : RGBA
Bit depth                                : 8 bits
Compression mode                         : Lossless
Stream size                              : 1.84 MiB (100%)
Gamma                                    : 0.455
```

**Comment by zDEFz** [comment]
I have specifically

```bash
output $L {
    color_profile srgb 
    mode 1920x1080@144Hz transform 270 position 0 0
    background /home/blu/.config/sway/wallpaper/DP-2/1.png fill
    resolution 1920x1080
    }
output $R {
    color_profile srgb 
    mode 1920x1080@144Hz position 1080 270
    background /home/blu/.config/sway/wallpaper/DP-1/2.png fill
    resolution 1920x1080
}

````

**Comment by gergo-salyi** [comment]
I added a few lines of code to try to support for 90 degree rotated displays. (I'm not 100% sure that all "output transforms" will be handled correctly yet, but let's try this for now.)

I released 0.1.9, could you please test it and then tell me here if it works well for you now?

**Comment by zDEFz** [comment]
> I added a few lines of code to try to support for 90 degree rotated displays. (I'm not 100% sure that all "output transforms" will be handled correctly yet, but let's try this for now.)
> 
> I released 0.1.9, could you please test it and then tell me here if it works well for you now?

```bash

error[E0425]: cannot find function `size_of` in this scope
   --> /home/blu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fast_image_resize-5.0.0/src/resizer.rs:283:15
    |
283 |             * size_of::<u8>()
    |               ^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
1   + use core::mem::size_of;
    |
1   + use std::mem::size_of;
    |

For more information about this error, try `rustc --explain E0425`.
error: could not compile `fast_image_resize` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by gergo-salyi** [comment]
I think this is an older bug in Rust. Depending on how you have Rust installed:

- if you have `rust` or `cargo` from a disro package then upgrade your system,
- if you have `rustup` then run `$ rustup update`

Finally verify that `$ rustc --version` gives you 1.80 or newer (I think 1.79 and below is bugged).

If you have a situation where you cannot update to Rust 1.80 or newer please tell me, because I have to find another way because other people will have problems whit this too...

**Comment by zDEFz** [comment]
stable-x86_64-unknown-linux-gnu updated - rustc 1.81.0 (eeb90cda1 2024-09-04) (from rustc 1.79.0 (129f3b996 2024-06-10)) => compiles

Please touch up the PKGBUILD in the AUR to have this check in place.

Great. It works now. Thanks a lot.

**Comment by gergo-salyi** [comment]
> Great. It works now. Thanks a lot.

Nice. Thank you for reporting this and then testing.
.

> Please touch up the PKGBUILD in the AUR to have this check in place.

I added `rust-version = "1.80"` to `Cargo.toml` in commit 2c919312 here so the build will fail with a better error in the future if minimum Rust version is not met. I'm not making a new release now just because of this if you don't mind. 

People who have `rust` installed from the distro should never be on a lower version now anyways. A clean chroot build also provides this.

For people who have `rustup` I don't know how to enforce that from PKGBUILD. Things like `makedepends=('cargo>=1.80')` won't work because `rustup` doesn't give `cargo` / `rustc` in ways how `pacman` can understand their version. So I think `rust-version = "1.80"` in `Cargo.toml` enforced by `cargo` will be enough.

But just tell me if you have an idea what to change in PKGBUILD.
.

> The wallpaper applies to all my workspaces on the suitable screen. I do not yet plan to use blank wallpapers for those that aren't defined.

I'm not sure I understand. The way to define a **fallback wallpaper** for the workspaces you don't want give a specific named wallpaper is in the README:

> ***Can define a fallback wallpaper with the special name: _default***

```
~/my_wallpapers
    ├─ eDP-1
    │    ├─ _default.jpg
    │    ├─ 1.jpg
    │    ├─ 2.png
    └─ HDMI-A-1
         ├─ _default.png
         ├─ 1.jpg
         └─ 3.png
```

Is there a problem after you put a `_default.jpg` or `_default.png` fallback wallpaper in the wallpaper directory of your displays? Or what feature do you need apart from what having `_default.jpg` does now?

**Comment by zDEFz** [comment]
> I'm not sure I understand. The way to define a **fallback wallpaper** for the workspaces you don't want give a specific named wallpaper is in the README:
> 
> > _**Can define a fallback wallpaper with the special name: _default**_
> 
> ```
> ~/my_wallpapers
>     ├─ eDP-1
>     │    ├─ _default.jpg
>     │    ├─ 1.jpg
>     │    ├─ 2.png
>     └─ HDMI-A-1
>          ├─ _default.png
>          ├─ 1.jpg
>          └─ 3.png
> ```
> 
> Is there a problem after you put a `_default.jpg` or `_default.png` fallback wallpaper in the wallpaper directory of your displays? Or what feature do you need apart from what having `_default.jpg` does now?

Oh now I understand what default.jpg|png is for.
Well, there is no problem per-se, it's just a tidbit.
It would been nicer if we could specify simply a color for workspaces that do not have background wallpapers.

But that's a design choice and up to you.

Theres no issue then.

**Comment by gergo-salyi** [comment]
I will think about adding a `--fallback-background-color` command line option to set a solid color if there is no `_default` wallpaper file found. Maybe in the future.

Thank you again! Closing then.
